.test:
  cache:
    paths:
    - node_modules
  coverage: '/^Statements *: (\d+\.\d+%)/'
  script:
  - npm install
  - npm test

test:node14:
  extends: .test
  cache:
    key: node14
  image: node:14-alpine

test:node8:
  extends: .test
  cache:
    key: node8
  image: node:8-alpine
